### ISSUE TITLE
属性缩进怎么调整?

### ISSUE THREAD

**Issue by ChendayUP** [phonycode/wxml-vscode#13]
属性缩进怎么调整?
<img width="1052" alt="WeChatd1969b4c9ef1aed297d7129570606196" src="https://user-images.githubusercontent.com/20022523/55716085-aed69180-5a28-11e9-93ec-97fc0693ec95.png">

**Comment by cnyballk** [comment]
wxmlConfig.format的indent_size属性，当"indent_with_tabs": false时起效

**Comment by ChendayUP** [comment]
<img width="547" alt="WeChat8e78a785b2eaf42ccb4dd980514c1310" src="https://user-images.githubusercontent.com/20022523/55791175-84e8a200-5af0-11e9-8e16-482a2592c809.png">
红框没有缩进了,有问题了,绿框里面对了

**Comment by cnyballk** [comment]
这个可以设置"indent_char": " "

**Comment by ChendayUP** [comment]
可以了,完美
