### ISSUE TITLE
不能格式化

### ISSUE THREAD

**Issue by leo95123** [phonycode/wxml-vscode#23]
![image](https://user-images.githubusercontent.com/28439527/78639314-4bec3480-78e0-11ea-9002-ca1456897fe6.png)
![image](https://user-images.githubusercontent.com/28439527/78639329-55759c80-78e0-11ea-9e78-b1cc68ab1bb4.png)

**Comment by cnyballk** [comment]
具体步骤可以描述一下不？

**Comment by leo95123** [comment]
可以右键或者通过命令行格式化，但是不能通过ALT+SHIFT+F进行格式化，我现在用了minapp + prettier 代替。

**Comment by cnyballk** [comment]
了解，现在prettier好用了吗？

**Comment by leo95123** [comment]
感觉很好用
